# Only the keys the backend needs
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hw-backend-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: hw-backend-prod
    creationPolicy: Owner
  data:
    - secretKey: JWT_KEY
      remoteRef:
        key: prod/backend
        property: JWT_KEY
    - secretKey: PROD_DB_USERNAME
      remoteRef:
        key: rds!db-9d932bc7-f80d-46e3-80b3-4eeec7580ace
        property: username
    - secretKey: PROD_DB_PASSWORD
      remoteRef:
        key: rds!db-9d932bc7-f80d-46e3-80b3-4eeec7580ace
        property: password
