apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.11.0
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/argocd/prod/external-secrets/values.yml
    - repoURL: https://github.com/jelicki-jovan/k8s-envs.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # ESO CRDs are too large for client-side apply (last-applied annotation > 256 KB)
      - ServerSideApply=true
